[build]
  publish  = "public"
  command = "hugo"

  [build.environment]
    HUGO_VERSION = "0.120.3"
    HUGO_THEME = "hugo-theme-stack"

[context.production]
  command = "hugo"
  [context.production.environment]
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy_preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
    debug = true
