[build]
  publish  = "ryanhorricks2023/public"

[build.environment]
  HUGO_VERSION = "0.120.3"
  HUGO_THEME = "repo"

[context.production]
  command = "cd ryanhorricks2023 && hugo --gc --themesDir ../.. -b ${URL}"
  [context.production.environment]
    HUGO_ENV = "production"

[context.branch-deploy]
  command = "cd ryanhorricks2023 && hugoo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[context.deploy_preview]
  command = "cd ryanhorricks2023 && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
    debug = true
    srcdir = "ryanhorricks2023"
